// src/lib/components/Button.svelte
<script lang="ts">
    import type { Snippet } from 'svelte';

    interface Props {
        variant?: 'primary' | 'outline' | 'deep';
        size?: 'sm' | 'md' | 'lg';
        href?: string;
        target?: string;
        disabled?: boolean;
        children: Snippet;
    }

    let {
        variant = 'primary',
        size = 'md',
        href,
        target,
        disabled = false,
        children,
    }: Props = $props();

    const tag = $derived(href ? 'a' : 'button');
</script>

<svelte:element
    this={tag}
    {href}
    {target}
    {disabled}
    class="lal-btn lal-btn--{variant} lal-btn--{size}"
    rel={target === '_blank' ? 'noopener' : undefined}
>
    {@render children()}
</svelte:element>

<style lang="scss">
    .lal-btn {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        font-family: 'OverpassMono', monospace;
        font-weight: 700;
        letter-spacing: 0.1em;
        text-transform: uppercase;
        border-radius: 999px;
        cursor: pointer;
        text-decoration: none;
        white-space: nowrap;
        line-height: 1;
        transition:
            transform 140ms cubic-bezier(0.22, 1, 0.36, 1),
            background 240ms cubic-bezier(0.4, 0, 0.2, 1),
            color 240ms cubic-bezier(0.4, 0, 0.2, 1);

        &:active {
            transform: scale(0.97);
        }

        &:disabled {
            opacity: 0.45;
            cursor: not-allowed;
        }
    }

    /* Sizes — matching design system exactly */
    .lal-btn--sm {
        font-size: 12px;
        padding: 10px 22px;
    }

    .lal-btn--md {
        font-size: 14px;
        padding: 15px 34px;
    }

    .lal-btn--lg {
        font-size: 16px;
        padding: 20px 46px;
    }

    /* Variants */
    .lal-btn--primary {
        color: var(--theme-white);
        background-color: var(--theme-red);
        border: 3px solid var(--theme-red);

        &:hover {
            background-color: color-mix(in srgb, var(--theme-red) 85%, black);
            border-color: color-mix(in srgb, var(--theme-red) 85%, black);
        }
    }

    .lal-btn--outline {
        color: var(--theme-red);
        background: transparent;
        border: 3px solid var(--theme-red);

        &:hover {
            color: var(--theme-white);
            background-color: var(--theme-red);
        }
    }

    .lal-btn--deep {
        color: var(--theme-white);
        background-color: var(--theme-brown);
        border: 3px solid var(--theme-brown);

        &:hover {
            filter: brightness(0.9);
        }
    }
</style>

// design/html/components/core/Button.jsx
import React from "react";

/**
 * Lado a Lado primary action. A fully-rounded pill with an uppercase
 * Overpass Mono label. Filled (solid red/bordô) or outline (heavy ring).
 */
export function Button({
  children,
  variant = "primary",   // "primary" | "deep" | "outline" | "outline-light" | "ghost"
  size = "md",           // "sm" | "md" | "lg"
  as = "button",
  disabled = false,
  style = {},
  ...rest
}) {
  const sizes = {
    sm: { padding: "10px 22px", fontSize: "12px" },
    md: { padding: "15px 34px", fontSize: "14px" },
    lg: { padding: "20px 46px", fontSize: "16px" },
  };
  const variants = {
    primary: { background: "var(--accent)", color: "var(--text-on-accent)", boxShadow: "none", border: "var(--border-width-strong) solid var(--accent)" },
    deep:    { background: "var(--accent-deep)", color: "var(--text-on-footer)", border: "var(--border-width-strong) solid var(--accent-deep)" },
    outline: { background: "transparent", color: "var(--accent)", border: "var(--border-width-strong) solid var(--accent)" },
    "outline-light": { background: "transparent", color: "var(--lal-bege)", border: "var(--border-width-strong) solid var(--lal-bege)" },
    ghost:   { background: "transparent", color: "var(--accent)", border: "var(--border-width-strong) solid transparent" },
  };
  // On hover, transparent variants fill in so it's obvious the cursor is over them.
  const hovers = {
    primary: { background: "var(--accent-hover)", color: "var(--text-on-accent)" },
    deep:    { background: "var(--accent-deep)", color: "var(--text-on-footer)", filter: "brightness(0.9)" },
    outline: { background: "var(--accent)", color: "var(--text-on-accent)" },
    "outline-light": { background: "var(--lal-bege)", color: "var(--accent-deep)" },
    ghost:   { background: "var(--accent)", color: "var(--text-on-accent)" },
  };
  const base = variants[variant];
  const hover = hovers[variant] || {};
  const applyHover = (el) => {
    el.style.background = hover.background ?? base.background;
    if (hover.color) el.style.color = hover.color;
    el.style.filter = hover.filter ?? "none";
  };
  const clearHover = (el) => {
    el.style.background = base.background;
    el.style.color = base.color;
    el.style.filter = "none";
    el.style.transform = "scale(1)";
  };
  const Tag = as;
  return (
    <Tag
      disabled={as === "button" ? disabled : undefined}
      style={{
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        gap: "10px",
        fontFamily: "var(--font-mono)",
        fontWeight: 700,
        letterSpacing: "0.1em",
        textTransform: "uppercase",
        textDecoration: "none",
        borderRadius: "var(--radius-pill)",
        cursor: disabled ? "not-allowed" : "pointer",
        opacity: disabled ? 0.45 : 1,
        transition: "transform var(--dur-fast) var(--ease-out), background var(--dur-base) var(--ease-soft), filter var(--dur-base) var(--ease-soft)",
        whiteSpace: "nowrap",
        lineHeight: 1,
        ...sizes[size],
        ...variants[variant],
        ...style,
      }}
      onMouseDown={(e) => { if (!disabled) e.currentTarget.style.transform = "scale(0.97)"; }}
      onMouseUp={(e) => { e.currentTarget.style.transform = "scale(1)"; }}
      onMouseEnter={(e) => { if (!disabled) applyHover(e.currentTarget); }}
      onMouseLeave={(e) => { clearHover(e.currentTarget); }}
      {...rest}
    >
      {children}
    </Tag>
  );
}
