// src/lib/components/FeatureBand.svelte
﻿<script lang="ts">
    import type { Snippet } from 'svelte';

    interface Props {
        children: Snippet;
    }

    let { children }: Props = $props();
</script>

<div class="lal-feature-band">
    <div class="lal-feature-band__inner font-display flex-wrap whitespace-normal text-[1.15rem] sm:flex-nowrap sm:whitespace-nowrap sm:text-[clamp(0.95rem,2vw,1.7rem)]">
        {@render children()}
    </div>
</div>

<style lang="scss">
    .lal-feature-band {
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 2rem;
        flex-wrap: wrap;
        padding: 1.5rem var(--container-pad);
        width: 100%;
        box-sizing: border-box;
        background: var(--theme-yellow);
    }

    .lal-feature-band__inner {
        font-weight: 500;
        font-style: italic;
        font-size: clamp(0.95rem, 2vw, 1.7rem);
        line-height: 1.2;
        text-align: center;
        color: var(--theme-brown);
        display: inline-flex;
        flex-wrap: nowrap;
        white-space: nowrap;
        align-items: center;
        justify-content: center;
        gap: 0.3em;
    }
</style>

// design/html/components/core/FeatureBand.jsx
import React from "react";

/**
 * Full-bleed yellow feature band — the brand's recurring divider that
 * carries a short script/serif statement ("E viveram lado a lado para
 * sempre") and an optional action. Defaults to the signature yellow.
 */
export function FeatureBand({ children, action, tone = "yellow", align = "center", style = {} }) {
  const tones = {
    yellow: { background: "var(--surface-band)", color: "var(--text-on-band)" },
    bordo:  { background: "var(--surface-footer)", color: "var(--text-on-footer)" },
  };
  return (
    <div style={{
      display: "flex",
      alignItems: "center",
      justifyContent: align === "center" ? "center" : "space-between",
      gap: "32px",
      flexWrap: "wrap",
      padding: "40px var(--container-pad)",
      width: "100%",
      boxSizing: "border-box",
      ...tones[tone],
      ...style,
    }}>
      <div style={{
        fontFamily: "var(--font-display)",
        fontWeight: 500,
        fontStyle: "italic",
        fontSize: "clamp(1.6rem, 3vw, 2.4rem)",
        lineHeight: 1.1,
        textAlign: align,
      }}>
        {children}
      </div>
      {action}
    </div>
  );
}
