// design/html/components/core/Tag.jsx
import React from "react";

/**
 * Small rounded label/chip. Used for categories, dates, statuses.
 */
export function Tag({ children, tone = "red", style = {}, ...rest }) {
  const tones = {
    red:    { background: "var(--lal-vermelho)", color: "var(--lal-bege)" },
    bordo:  { background: "var(--lal-bordo)",    color: "var(--lal-bege)" },
    yellow: { background: "var(--lal-amarelo)",  color: "var(--lal-bordo)" },
    cream:  { background: "var(--lal-bege)",     color: "var(--lal-bordo)", boxShadow: "inset 0 0 0 1.5px var(--border-hairline)" },
    outline:{ background: "transparent",         color: "var(--lal-vermelho)", boxShadow: "inset 0 0 0 1.5px var(--lal-vermelho)" },
  };
  return (
    <span
      style={{
        display: "inline-flex",
        alignItems: "center",
        gap: "6px",
        fontFamily: "var(--font-mono)",
        fontWeight: 600,
        fontSize: "11px",
        letterSpacing: "0.08em",
        textTransform: "uppercase",
        padding: "6px 12px",
        borderRadius: "var(--radius-pill)",
        lineHeight: 1,
        ...tones[tone],
        ...style,
      }}
      {...rest}
    >
      {children}
    </span>
  );
}

// src/lib/components/Tag.svelte
<script lang="ts">
    import type { Snippet } from 'svelte';

    interface Props {
        tone?: 'red' | 'yellow' | 'outline';
        children: Snippet;
    }

    let { tone = 'outline', children }: Props = $props();
</script>

<span class="lal-tag lal-tag--{tone}">
    {@render children()}
</span>

<style lang="scss">
    .lal-tag {
        display: inline-flex;
        align-items: center;
        gap: 6px;
        font-family: 'OverpassMono', monospace;
        font-weight: 600;
        font-size: 11px;
        letter-spacing: 0.08em;
        text-transform: uppercase;
        padding: 6px 12px;
        border-radius: 999px;
        white-space: nowrap;
        line-height: 1;
    }

    .lal-tag--red {
        color: var(--theme-cream);
        background-color: var(--theme-red);
    }

    .lal-tag--yellow {
        color: var(--theme-brown);
        background-color: var(--theme-yellow);
    }

    .lal-tag--outline {
        color: var(--theme-red);
        background: transparent;
        box-shadow: inset 0 0 0 1.5px var(--theme-red);
    }
</style>
